field: 6ae50bdf-3ba3-43a5-abc7-629ba49bb875
fieldLayouts:
  a2b8598d-1f52-4615-8077-c8f9b88ec4dc:
    tabs:
      -
        elements:
          -
            fieldUid: ddc3c1f2-c351-421f-bd98-9dd739c6fdf7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7c7c3a7-cad0-450d-aa8e-d8725e964822
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8da09820-cfaa-4a7e-8508-c97ab972f504
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4479a108-aaa8-4a5b-9e38-b2b753ce5ea7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7e2b353-7b2f-4d9a-841c-f74538b50880
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4479a108-aaa8-4a5b-9e38-b2b753ce5ea7:
    contentColumnType: string
    fieldGroup: null
    handle: blockImage
    instructions: ''
    name: 'Block Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:7015b8d6-6d31-41d1-9b00-cad0955939aa'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7015b8d6-6d31-41d1-9b00-cad0955939aa'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:7015b8d6-6d31-41d1-9b00-cad0955939aa'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8da09820-cfaa-4a7e-8508-c97ab972f504:
    contentColumnType: text
    fieldGroup: null
    handle: blockLink
    instructions: ''
    name: 'Block Link'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Link
                -
                  - handle
                  - link
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Name
                -
                  - handle
                  - name
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: '1'
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  a7c7c3a7-cad0-450d-aa8e-d8725e964822:
    contentColumnType: text
    fieldGroup: null
    handle: blockDescription
    instructions: ''
    name: 'Block Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a7e2b353-7b2f-4d9a-841c-f74538b50880:
    contentColumnType: boolean
    fieldGroup: null
    handle: blockImagePosition
    instructions: ''
    name: 'Block Image Position'
    searchable: false
    settings:
      default: false
      offLabel: Left
      onLabel: Right
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ddc3c1f2-c351-421f-bd98-9dd739c6fdf7:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: 'Block Title'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: leftRightImageWithText
name: 'Left/Right image with text'
sortOrder: 2
