field: 6ae50bdf-3ba3-43a5-abc7-629ba49bb875
fieldLayouts:
  873eb678-c2a3-40a1-8289-834c328061dc:
    tabs:
      -
        elements:
          -
            fieldUid: 02eb906e-d3d5-488d-a3cd-e39a9374b182
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  02eb906e-d3d5-488d-a3cd-e39a9374b182:
    contentColumnType: string
    fieldGroup: null
    handle: partnersLogo
    instructions: ''
    name: 'Partner''s Logo'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - b91bbe03-6b1b-4e49-ba80-a91881d6fbbf
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 92b12040-7948-4ba3-b46a-e991db1cd7e2
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c139ebce-2b7a-4924-b9f3-937448bfc4bc
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_partnerslogo}}'
      fieldLayout: table
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: partners
name: Partners
sortOrder: 3
