field: 6ae50bdf-3ba3-43a5-abc7-629ba49bb875
fieldLayouts:
  e3c4f3a8-4c72-432a-a01a-c165893b88b2:
    tabs:
      -
        elements:
          -
            fieldUid: 16ff0469-8142-4063-a889-3570da21e6a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3d4cace1-9011-4544-a315-46d9505bf189
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 37245692-7526-4e54-aef9-b3f46002b03c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  16ff0469-8142-4063-a889-3570da21e6a9:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: 'Block Title'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  37245692-7526-4e54-aef9-b3f46002b03c:
    contentColumnType: string
    fieldGroup: null
    handle: blockIconItems
    instructions: 'You can find icon names there http://project-digital.bronskiy.com/assets/fonts/fontello/demo.html'
    name: 'Block Icon Items'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - dd0fe519-7699-4923-8997-1f51a6fad56d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 72fa09b3-b575-45fb-915a-c3a84bfb538c
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_9_blockiconitems}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  3d4cace1-9011-4544-a315-46d9505bf189:
    contentColumnType: text
    fieldGroup: null
    handle: blockDescription
    instructions: ''
    name: 'Block Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textWithIconItems
name: 'Text with icon items'
sortOrder: 9
