fieldLayouts:
  12568106-a63a-410c-af51-3b01f2e1f088:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: examples
hasUrls: true
name: Examples
settings:
  path: '@webroot/images/examples'
sortOrder: 4
type: craft\volumes\Local
url: /images/examples
