field: fbf247bf-efe3-4c05-b0a6-d1b8f60b50bb
fieldLayouts:
  c2fb2582-f3a9-4dd2-bbd3-f11e4d295d1f:
    tabs:
      -
        elements:
          -
            fieldUid: 8e164381-5f0f-42e9-a65e-b15b80c196b2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9a5615a7-147d-489d-b974-0c078754fda1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3318fa22-7a60-4391-b54f-2846a3a7401b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3318fa22-7a60-4391-b54f-2846a3a7401b:
    contentColumnType: string
    fieldGroup: null
    handle: featureItemImage
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:7015b8d6-6d31-41d1-9b00-cad0955939aa'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7015b8d6-6d31-41d1-9b00-cad0955939aa'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8e164381-5f0f-42e9-a65e-b15b80c196b2:
    contentColumnType: text
    fieldGroup: null
    handle: featureItemName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9a5615a7-147d-489d-b974-0c078754fda1:
    contentColumnType: text
    fieldGroup: null
    handle: featureItemDescription
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple-Mod.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
