field: 37245692-7526-4e54-aef9-b3f46002b03c
fieldLayouts:
  90b17450-c15a-4757-8a11-6d26bdbcf954:
    tabs:
      -
        elements:
          -
            fieldUid: dd0fe519-7699-4923-8997-1f51a6fad56d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 72fa09b3-b575-45fb-915a-c3a84bfb538c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  72fa09b3-b575-45fb-915a-c3a84bfb538c:
    contentColumnType: text
    fieldGroup: null
    handle: iconName
    instructions: 'You can find icon names there http://project-digital.bronskiy.com/assets/fonts/fontello/demo.html'
    name: 'Icon Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd0fe519-7699-4923-8997-1f51a6fad56d:
    contentColumnType: text
    fieldGroup: null
    handle: iconDescription
    instructions: ''
    name: 'Icon Description'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
