fieldLayouts:
  76934439-dba5-49c7-9941-229c34af8313:
    tabs:
      -
        elements:
          -
            fieldUid: 74a11a7f-d6fe-4b42-9f22-3342c1b834d8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6be3a191-f6b5-4d7d-8e53-4ca40997aa45
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d15139e6-bdbe-4f63-a90a-da1f973dace8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: globalSeo
name: 'Global SEO'
