enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  fceaf36c-696c-425f-9b59-6c38305a1e8d:
    enabledByDefault: true
    hasUrls: true
    template: contact/index
    uriFormat: contact
type: single
