enableVersioning: true
handle: examples
name: Examples
propagationMethod: all
siteSettings:
  fceaf36c-696c-425f-9b59-6c38305a1e8d:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'examples/{slug}'
type: channel
