enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  fceaf36c-696c-425f-9b59-6c38305a1e8d:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
